#! /usr/bin/env bash

# helper script to generate new applications from template
# ideas:
# ask for short-name of new application
# copy templates from template directory
# 
# interactive mode to fill out cover letter
# add placerholders in typst document
# compile cover letter with typst
# give url as an argument to the job listing to archive it automatically
# curl url and create pdf from output?

# make sure the expected folders are in this directory

ask() {
    # while loop for when adding validation/options
    while true ; do
        read -r -p "$1: " result
        # no result/skipped
        #if [[ -z $result ]]; then
        #    ask_result=""
        #fi
        ask_result=$result
        return

    done
}

outdir="./out/"

### check preconditions

if ! [[ -e "./template" ]]; then
	echo "template folder not found" >&2
    exit 1
fi


if ! [[ -e "./assets" ]]; then
	echo "assets folder not found" >&2
    exit 1
fi

# check if typst exists
if ! command -v typst &> /dev/null ; then
    echo "typst not found. Is it installed?"
    exit 1
fi

# check if outdir exists
#if ! [[ -e $outdir ]]; then
#    echo "output directory $outdir not found, creating it..."
#    mkdir $outdir
#fi


### create application directory

# creates a directory for this applicatio in the out folder
ask "dir name for this application: "
application_name=$ask_result
echo "folder name for this application is $application_name"
app_path="$outdir$application_name"

# make sure dir does not exist
if [[ -e "$app_path" ]]; then
	echo "application name at location $app_path already exists" >&2
	exit 1
else
	echo "$app_path is available!"
fi

# create application directory
#mkdir -p $app_path


### copy over template files

# copy typst templates
#cp template/* $app_path
# copy static assets
#cp assets/* $app_path
echo "Created new application at location $app_path"




# check if in interactive mode
if ! [[ $* == *-*i* ]]; then
	echo "done, interactive mode not enabled."
	exit 0
fi

echo "Starting interactive mode..."
sleep 2


clear

# prompt question
# save answer
# replace all placeholders with answers
# map answers to placeholders
# map placeholders to questions
# question -> answer -> placeholder
# placeholder -> question; placeholder -> answer


echo ""
echo "What language will this be written in?"
echo "(Does not change this scirpt's text)"
echo ""
ask "Language? (en/de)"
PLACEHOLDER_LANG_STR=$ask_result


echo ""
echo "RECIPIENT ADDRESS" 
echo "Recipient Line 1 (Name)"
echo ""

ask "Name"
PLACEHOLDER_RECIPIENT_NAME=$ask_result

echo ""
echo "Recipient Line 2 (Name, additional)"
echo ""

ask "Name, second line"
PLACEHOLDER_RECIPIENT_NAME2=$ask_result

echo ""
echo "Recipient Street and house number"
echo ""
ask "street"
PLACEHOLDER_RECIPIENT_STREET=$ask_result

echo ""
echo "Recipient postcode and city"
echo ""
ask "city"
PLACEHOLDER_RECIPIENT_POSTCODE=$ask_result

echo ""
echo "Recipient country"
echo ""
ask "country"
PLACEHOLDER_RECIPIENT_COUNTRY=$ask_result

echo ""
echo ""
echo "Starting with the letter itself."
echo "What is the subject of this letter?"
echo "Ex: Application as Software Engineer"
echo ""

ask "Subject"
PLACEHOLDER_SUBJECT_STR=$ask_result

echo ""
echo "Opening Paragraph"
echo "Include where you found the application, the job title you are applying for, "
echo "interest and appeal quickly and succinctly (what you bring to the table)."
echo ""
# TODO example
ask "Opening"
PLACEHOLDER_OPENING=$ask_result

echo ""
echo "Main Body"
echo "Highlight relevant background, key achievements, skills and specialties."
echo "Should be relevant to position or at least the field, focus on 1-2 details with measurable impact."
echo ""
# TODO example
ask "Main"
PLACEHOLDER_MAIN=$ask_result

echo ""
echo "Closing Paragraph"
echo "Final key achievemt or skill."
echo "Summarise a specific story or anecdote and show transferable skills or relatable experiences."
echo ""
# TODO example
ask "Closing"
PLACEHOLDER_CLOSING=$ask_result

echo ""
echo "Start Date"
echo "When can you begin?"
echo "Ex: 2026-02-01 | 01.02.2026"
echo ""

ask "Start"
PLACEHOLDER_STARTDATE=$ask_result


echo "Done! Unfortunately, the rest is not yet implemented"
# TODO replace variables in letter template
# TODO compile letter template
# TODO ask to open compiled letter
# TODO show errors if compilation failed






# for later
# initial compile and open pdf in background
#typst compile $app_path/letter.typ && open $app_path/letter.pdf &

# start watching pdf in background
#echo "starting background watch"
#typst watch $app_path/letter.typ &




